import {
  baklava_desktop,
  baklava_mobile,
  baklava_tablet,
  baklava_thumbnail,
  brownie_desktop,
  brownie_mobile,
  brownie_tablet,
  brownie_thumbnail,
  brulee_desktop,
  brulee_mobile,
  brulee_tablet,
  brulee_thumbnail,
  cake_desktop,
  cake_mobile,
  cake_tablet,
  cake_thumbnail,
  cotta_desktop,
  cotta_mobile,
  cotta_tablet,
  cotta_thumbnail,
  macaron_desktop,
  macaron_mobile,
  macaron_tablet,
  macaron_thumbnail,
  pie_desktop,
  pie_mobile,
  pie_tablet,
  pie_thumbnail,
  tiramisu_desktop,
  tiramisu_mobile,
  tiramisu_tablet,
  tiramisu_thumbnail,
  waffle_desktop,
  waffle_mobile,
  waffle_tablet,
  waffle_thumbnail,
} from "./assets/images";

export const mydata = [
  {
    image: {
      thumbnail: waffle_thumbnail,
      mobile: waffle_mobile,
      tablet: waffle_tablet,
      desktop: waffle_desktop,
    },
    name: "Waffle with Berries",
    category: "Waffle",
    price: 6.5,
    id: 1,
  },
  {
    image: {
      thumbnail: brulee_thumbnail,
      mobile: brulee_mobile,
      tablet: brulee_tablet,
      desktop: brulee_desktop,
    },
    name: "Vanilla Bean Crème Brûlée",
    category: "Crème Brûlée",
    price: 7.0,
    id: 2,
  },
  {
    image: {
      thumbnail: macaron_thumbnail,
      mobile: macaron_mobile,
      tablet: macaron_tablet,
      desktop: macaron_desktop,
    },
    name: "Macaron Mix of Five",
    category: "Macaron",
    price: 8.0,
    id: 3,
  },
  {
    image: {
      thumbnail: tiramisu_thumbnail,
      mobile: tiramisu_mobile,
      tablet: tiramisu_tablet,
      desktop: tiramisu_desktop,
    },
    name: "Classic Tiramisu",
    category: "Tiramisu",
    price: 5.5,
    id: 4,
  },
  {
    image: {
      thumbnail: baklava_thumbnail,
      mobile: baklava_mobile,
      tablet: baklava_tablet,
      desktop: baklava_desktop,
    },
    name: "Pistachio Baklava",
    category: "Baklava",
    price: 4.0,
    id: 5,
  },
  {
    image: {
      thumbnail: pie_thumbnail,
      mobile: pie_mobile,
      tablet: pie_tablet,
      desktop: pie_desktop,
    },
    name: "Lemon Meringue Pie",
    category: "Pie",
    price: 5.0,
    id: 6,
  },
  {
    image: {
      thumbnail: cake_thumbnail,
      mobile: cake_mobile,
      tablet: cake_tablet,
      desktop: cake_desktop,
    },
    name: "Red Velvet Cake",
    category: "Cake",
    price: 4.5,
    id: 7,
  },
  {
    image: {
      thumbnail: brownie_thumbnail,
      mobile: brownie_mobile,
      tablet: brownie_tablet,
      desktop: brownie_desktop,
    },
    name: "Salted Caramel Brownie",
    category: "Brownie",
    price: 4.5,
    id: 8,
  },
  {
    image: {
      thumbnail: cotta_thumbnail,
      mobile: cotta_mobile,
      tablet: cotta_tablet,
      desktop: cotta_desktop,
    },
    name: "Vanilla Panna Cotta",
    category: "Panna Cotta",
    price: 6.5,
    id: 9,
  },
];
